service: housing-group-functions

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - lambda:*
                      - secretsmanager:*
                  Resource:
                      - arn:aws:lambda:us-east-1:*:*
                      - arn:aws:secretsmanager:us-east-1:*:*

plugins:
    - ./vendor/bref/bref

functions:
    post-offer:
        handler: post-offer.php
        description: ""
        timeout: 28
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: ANY /post-offer/
            - http: ANY /post-offer/{proxy+}

package:
    patterns:
        - "!.idea/**"
        - "!node_modules/**"
        - "!tests/**"
        - "!*.md"
        - "!*.js"
        - "!**/.DS_Store"
        - "!email.json"
        - "!update-email-credential.php"
