service: housing-group-functions

provider:
    name: aws
    region: us-east-1
    runtime: provided
    iamRoleStatements:
        - Effect: Allow
          Action:
              - lambda:InvokeFunction
          Resource:
              - arn:aws:lambda:us-east-1:*:*

plugins:
    - ./vendor/bref/bref

functions:
    mail-api:
        handler: mail-api.php
        description: ""
        timeout: 28
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: ANY /mail-api/
            - http: ANY /mail-api/{proxy+}

    post-offer-demo:
        handler: post-offer-demo.php
        description: ""
        timeout: 28
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: ANY /post-offer-demo/
            - http: ANY /post-offer-demo/{proxy+}

    post-offer:
        handler: post-offer.php
        description: ""
        timeout: 28
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: ANY /post-offer/
            - http: ANY /post-offer/{proxy+}

    post-offer-styled:
        handler: post-offer-styled.php
        description: ""
        timeout: 28
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: ANY /post-offer-styled/
            - http: ANY /post-offer-styled/{proxy+}

package:
    exclude:
        - ".idea/**"
        - "node_modules/**"
        - "tests/**"
        - "*.md"
        - "*.js"
        - "**/.DS_Store"
